Change location for loading thebe and make it always load the latest version.
LibreTexts/ckeditor-binder-plugin pull request #130
Opened 2020-12-23 11:52 UTC by moorepants

2020-12-23 11:53 UTC, moorepants commented
@narrator0 can you review? If you don't think using latest is smart we can manually increment the version number.

2020-12-23 21:12 UTC, narrator0 commented
I would go for `0.6.0` since I don't think it is stable enough. Don't want libretexts pages to fail because of this.

2020-12-29 00:54 UTC, celine168 commented
I agree with 0.6.0.

2020-12-29 00:56 UTC, celine168 requested changes

2020-12-29 00:56 UTC, celine168 commented on src/scripts/activateThebelab.js
> +    loadScript('https://unpkg.com/thebe@latest/lib/index.js')
```suggestion
    loadScript('https://unpkg.com/thebe@0.6.0/lib/index.js')
```

2020-12-29 08:50 UTC, moorepants commented
I committed the suggestion.

2020-12-29 16:57 UTC, celine168 approved these changes

2021-01-06 19:20 UTC, moorepants commented
This is good to go in @LibreTexts/jupyter-team .

2021-01-06 21:00 UTC, merged