Use global var to get widget from dialog
LibreTexts/ckeditor-binder-plugin pull request #48
Opened 2020-02-19 00:26 UTC by narrator0

### What Happened?

`dialog.getModel` doesn't work on production. This is only supported on older versions. It is set [here](https://github.com/ckeditor/ckeditor4/blob/master/plugins/widget/plugin.js#L1217) on the `edit` events of the widgets.

### How it is solved

Set `window.currentWidget` on `edit` events of the widgets so that the dialog can access it. I understand this is a bad fix to use global variables. However, under time limits, this is the only fix I can think of right now.

@celine168 It is currently test deployed. You can see how it works on production.

2020-02-19 00:51 UTC, moorepants commented
"bad fix to use global variables", it's only bad if it can be clobbered easily. It is possible to design safely. Making the variable name very unique can help.

2020-02-19 20:33 UTC, celine168 commented
@moorepants  I do think that `currentWidget` is a good name, but if you want it to be more unique, then maybe something like `currentThebelabWidget` would suffice.

2020-02-19 20:46 UTC, celine168 requested changes
I will approve after the naming gets resolved. Otherwise, the widget works as intended, good job!

2020-02-19 20:46 UTC, celine168 commented on src/scripts/dialog.js
> +    const widget = window.currentWidget;
```suggestion
    const widget = window.currentThebelabWidget;
```
@moorepants I believe this naming convention is unique enough.

2020-02-19 21:46 UTC, moorepants commented
Mine was just a general comment. The name is unique enough.

2020-02-19 23:21 UTC, narrator0 commented
Consider there are multiple widgets and dialogs on production. Add used `currentEditedThebelabWidgetByBinderDialog` to be really specific. However, I still think potentially upgrading to the newer CKEditor would be the correct way to do.

2020-02-20 02:17 UTC, celine168 approved these changes
Approving!

2020-02-22 00:33 UTC, merged